//go:build ignore

// gen_icons builds icons.svg, the one SVG sprite every page draws its icons
// from, out of Lucide (https://lucide.dev, ISC licence, see
// static/icons.LICENSE.txt). Run it from internal/web after adding a name
// below:
//
//	go run gen_icons.go
//
// Each icon becomes a <symbol id="name">; views.Icon references it with
// <use href="/static/icons.svg#name">. The stroke width is set here once
// (1.75, per the design brief) and the colour is currentColor.
package main

import (
	"fmt"
	"io"
	"net/http"
	"os"
	"regexp"
	"strings"
)

// version pins the lucide-static release the sprite is built from.
const version = "1.48.0"

// names lists every icon the UI uses: device kinds and picker choices first,
// then interface icons. Keep views/icons.go in step.
var names = []string{
	// device kinds and the icon picker
	"laptop", "monitor", "ethernet-port", "router", "signal", "smartphone", "tablet",
	"server", "hard-drive", "printer", "lightbulb", "box", "container", "lock",
	"circle-help", "wifi", "satellite-dish", "cctv", "plug", "gamepad-2", "tv",
	"phone", "joystick", "satellite", "watch", "speaker", "thermometer", "house",
	// interface
	"search", "plus", "radar", "refresh-cw", "settings", "user", "log-out", "sun",
	"moon", "chevron-down", "chevron-right", "x", "check", "triangle-alert",
	"trash-2", "pencil", "external-link", "copy", "power", "network", "shield",
	"bell", "key", "list", "layout-grid", "clock", "filter", "ellipsis",
	"arrow-left", "download", "upload", "layout-dashboard", "activity", "sun-moon",
	"keyboard", "corner-down-left", "menu",
}

var (
	inner = regexp.MustCompile(`(?s)<svg[^>]*>(.*)</svg>`)
	space = regexp.MustCompile(`\s*\n\s*`)
)

func main() {
	var b strings.Builder
	fmt.Fprintf(&b, "<svg xmlns=\"http://www.w3.org/2000/svg\">\n")
	fmt.Fprintf(&b, "<!-- Generated by gen_icons.go from lucide-static %s (ISC, see icons.LICENSE.txt). Do not edit. -->\n", version)
	for _, n := range names {
		res, err := http.Get("https://cdn.jsdelivr.net/npm/lucide-static@" + version + "/icons/" + n + ".svg")
		if err != nil {
			fail(err)
		}
		src, err := io.ReadAll(res.Body)
		res.Body.Close()
		if err != nil || res.StatusCode != http.StatusOK {
			fail(fmt.Errorf("%s: status %d %v", n, res.StatusCode, err))
		}
		m := inner.FindSubmatch(src)
		if m == nil {
			fail(fmt.Errorf("%s: no <svg> element", n))
		}
		body := strings.TrimSpace(space.ReplaceAllString(string(m[1]), ""))
		fmt.Fprintf(&b, `<symbol id="%s" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">%s</symbol>`+"\n", n, body)
	}
	b.WriteString("</svg>\n")
	if err := os.WriteFile("static/icons.svg", []byte(b.String()), 0o644); err != nil {
		fail(err)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "gen_icons:", err)
	os.Exit(1)
}
