package main

import (
	"context"
	"database/sql"
	"errors"
	"flag"
	"fmt"
	"strings"

	"netis/internal/store"
)

// copyOrder lists every table in an order where a row's foreign-key targets
// have always been inserted already. The one exception is device's self
// reference (parent_device_id), which copyDevices handles with a second pass.
var copyOrder = []string{
	"subnet",
	"device",
	"iface",
	"tag",
	`"user"`,
	"ip_assignment",
	"iface_status",
	"availability_history",
	"open_port",
	"device_tag",
	"custom_field",
	"device_link",
	"event",
	"session",
	"setting",
	"integration_status",
}

// boolColumns names the columns SQLite stores as 0/1 integers and Postgres as
// BOOLEAN. Values in these columns are converted on the way across; every other
// column carries over as the driver returns it.
var boolColumns = map[string]map[string]bool{
	"subnet":             {"scan_enabled": true},
	"device":             {"reviewed": true},
	"iface_status":       {"online": true},
	"integration_status": {"ok": true},
}

// identityTables are the tables whose id is generated by Postgres. The import
// writes explicit ids to preserve every foreign-key reference, which leaves the
// identity sequences behind; they are advanced past the imported rows at the
// end so later inserts do not collide.
var identityTables = []string{
	"subnet", "device", "iface", "ip_assignment", "availability_history",
	"open_port", "tag", "custom_field", "device_link", "event", `"user"`,
}

// runMigrateDB copies a SQLite database into an empty Postgres database. It is
// a one-shot tool, not a live sync: run it with netis stopped, then restart
// netis with NETIS_DB pointing at the Postgres URL.
func runMigrateDB(ctx context.Context, args []string) error {
	fs := flag.NewFlagSet("netis migrate-db", flag.ContinueOnError)
	from := fs.String("from", "", "source SQLite database path")
	to := fs.String("to", "", "destination Postgres URL (postgres://…)")
	force := fs.Bool("force", false, "import even if the destination already holds rows")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *from == "" || *to == "" {
		fs.Usage()
		return errors.New("both -from and -to are required")
	}
	if store.IsPostgresDSN(*from) {
		return fmt.Errorf("-from must be a SQLite path, got a Postgres URL")
	}
	if !store.IsPostgresDSN(*to) {
		return fmt.Errorf("-to must be a Postgres URL (postgres://…), got %q", *to)
	}

	// Opening each store runs its own migrations, so the source is brought up
	// to the current schema before it is read and the destination has the
	// tables to receive it.
	src, err := store.Open(*from)
	if err != nil {
		return fmt.Errorf("open source: %w", err)
	}
	defer src.Close()
	dst, err := store.Open(*to)
	if err != nil {
		return fmt.Errorf("open destination: %w", err)
	}
	defer dst.Close()

	if !*force {
		if table, n, err := firstNonEmpty(ctx, dst.DB); err != nil {
			return err
		} else if n > 0 {
			return fmt.Errorf("destination is not empty (%s holds %d row(s)); "+
				"use -force to import anyway", table, n)
		}
	}

	tx, err := dst.DB.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()

	total := 0
	for _, table := range copyOrder {
		n, err := copyTable(ctx, src.DB, tx, table)
		if err != nil {
			return fmt.Errorf("copy %s: %w", table, err)
		}
		fmt.Printf("%-22s %6d row(s)\n", strings.Trim(table, `"`), n)
		total += n
	}
	if err := relinkDeviceParents(ctx, src.DB, tx); err != nil {
		return fmt.Errorf("relink device parents: %w", err)
	}
	for _, table := range identityTables {
		if err := resetIdentity(ctx, tx, table); err != nil {
			return fmt.Errorf("reset identity for %s: %w", table, err)
		}
	}
	if err := tx.Commit(); err != nil {
		return err
	}
	fmt.Printf("imported %d row(s) into %s\n", total, redactDSN(*to))
	return nil
}

// firstNonEmpty reports the first table in copyOrder that already holds rows.
func firstNonEmpty(ctx context.Context, db *sql.DB) (string, int, error) {
	for _, table := range copyOrder {
		var n int
		if err := db.QueryRowContext(ctx, `SELECT count(*) FROM `+table).Scan(&n); err != nil {
			return "", 0, err
		}
		if n > 0 {
			return strings.Trim(table, `"`), n, nil
		}
	}
	return "", 0, nil
}

// copyTable streams every row of one table from SQLite into Postgres, matching
// columns by name so the two schemas need only agree on names, not order.
// device's parent_device_id is written as NULL here and filled in afterwards by
// relinkDeviceParents, because a child row can precede its parent.
func copyTable(ctx context.Context, src *sql.DB, tx *sql.Tx, table string) (int, error) {
	rows, err := src.QueryContext(ctx, `SELECT * FROM `+table)
	if err != nil {
		return 0, err
	}
	defer rows.Close()
	cols, err := rows.Columns()
	if err != nil {
		return 0, err
	}

	quoted := make([]string, len(cols))
	placeholders := make([]string, len(cols))
	for i, c := range cols {
		quoted[i] = `"` + c + `"`
		placeholders[i] = fmt.Sprintf("$%d", i+1)
	}
	insert := fmt.Sprintf(`INSERT INTO %s (%s) VALUES (%s)`,
		table, strings.Join(quoted, ","), strings.Join(placeholders, ","))
	stmt, err := tx.PrepareContext(ctx, insert)
	if err != nil {
		return 0, err
	}
	defer stmt.Close()

	bools := boolColumns[strings.Trim(table, `"`)]
	n := 0
	for rows.Next() {
		vals := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range vals {
			ptrs[i] = &vals[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return n, err
		}
		for i, c := range cols {
			if bools[c] {
				vals[i] = toBool(vals[i])
			}
			if table == "device" && c == "parent_device_id" {
				vals[i] = nil
			}
		}
		if _, err := stmt.ExecContext(ctx, vals...); err != nil {
			return n, err
		}
		n++
	}
	return n, rows.Err()
}

// relinkDeviceParents restores parent_device_id once every device row exists.
func relinkDeviceParents(ctx context.Context, src *sql.DB, tx *sql.Tx) error {
	rows, err := src.QueryContext(ctx,
		`SELECT id,parent_device_id FROM device WHERE parent_device_id IS NOT NULL`)
	if err != nil {
		return err
	}
	defer rows.Close()
	type link struct{ id, parent int64 }
	var links []link
	for rows.Next() {
		var l link
		if err := rows.Scan(&l.id, &l.parent); err != nil {
			return err
		}
		links = append(links, l)
	}
	if err := rows.Err(); err != nil {
		return err
	}
	for _, l := range links {
		if _, err := tx.ExecContext(ctx,
			`UPDATE device SET parent_device_id=$1 WHERE id=$2`, l.parent, l.id); err != nil {
			return err
		}
	}
	return nil
}

// resetIdentity advances a table's id sequence past the highest imported id.
func resetIdentity(ctx context.Context, tx *sql.Tx, table string) error {
	_, err := tx.ExecContext(ctx, fmt.Sprintf(
		`SELECT setval(pg_get_serial_sequence('%s','id'),
			COALESCE((SELECT max(id) FROM %s),0)+1, false)`, table, table))
	return err
}

// toBool converts whatever the SQLite driver produced for a 0/1 column into a
// Go bool, so it can be bound to a Postgres BOOLEAN.
func toBool(v any) any {
	switch t := v.(type) {
	case nil:
		return nil
	case bool:
		return t
	case int64:
		return t != 0
	case float64:
		return t != 0
	case []byte:
		return len(t) > 0 && string(t) != "0"
	case string:
		return t != "" && t != "0"
	default:
		return v
	}
}

// redactDSN strips the password from a Postgres URL so it can be logged.
func redactDSN(dsn string) string {
	at := strings.LastIndex(dsn, "@")
	slashes := strings.Index(dsn, "//")
	if at < 0 || slashes < 0 || at < slashes {
		return dsn
	}
	userinfo := dsn[slashes+2 : at]
	if i := strings.Index(userinfo, ":"); i >= 0 {
		userinfo = userinfo[:i] + ":***"
	}
	return dsn[:slashes+2] + userinfo + dsn[at:]
}
