-- Postgres baseline: the schema as it stands after the SQLite migration
-- series 0001..0005. A Postgres database always starts empty (there is no
-- SQLite history to replay), so the five SQLite steps — two of which are
-- table rebuilds — collapse into this single file.
--
-- It is numbered 0005 deliberately: from here on both dialects share the same
-- migration numbers, so a future change is 0006_x.sql in each directory.
--
-- Type mapping from the SQLite originals:
--   INTEGER PRIMARY KEY -> BIGINT GENERATED BY DEFAULT AS IDENTITY. BY DEFAULT
--     rather than ALWAYS so `netis migrate-db` can insert explicit ids.
--   INTEGER used as a boolean -> BOOLEAN. pgx will not scan an int4 into a Go
--     bool, and these columns are scanned into bool fields.
--   REAL -> DOUBLE PRECISION.
--   strftime('%Y-%m-%dT%H:%M:%SZ','now') -> the to_char equivalent, so
--     timestamps keep the same RFC3339 text format on both backends.

CREATE TABLE subnet (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cidr TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL DEFAULT '',
  vlan_id BIGINT,
  kind TEXT NOT NULL DEFAULT 'lan' CHECK (kind IN ('lan','wireguard','proxmox-bridge')),
  scan_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  scan_interval_sec INTEGER NOT NULL DEFAULT 120
);

CREATE TABLE device (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  kind TEXT NOT NULL DEFAULT 'other' CHECK (kind IN
    ('computer','switch','router','modem','phone','server','printer','iot','vm','lxc','wg-peer','other')),
  notes TEXT NOT NULL DEFAULT '',
  vendor TEXT NOT NULL DEFAULT '',
  source TEXT NOT NULL DEFAULT 'manual' CHECK (source IN ('manual','scan','proxmox','wireguard','pihole')),
  parent_device_id BIGINT REFERENCES device(id) ON DELETE SET NULL,
  proxmox_vmid BIGINT,
  wg_pubkey TEXT,
  icon TEXT NOT NULL DEFAULT '',
  reviewed BOOLEAN NOT NULL DEFAULT FALSE,
  model TEXT NOT NULL DEFAULT '',
  function TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'))
);

CREATE TABLE iface (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id BIGINT NOT NULL REFERENCES device(id) ON DELETE CASCADE,
  mac TEXT,
  hostname TEXT
);
CREATE UNIQUE INDEX idx_iface_mac ON iface(mac) WHERE mac IS NOT NULL;

CREATE TABLE ip_assignment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  iface_id BIGINT NOT NULL REFERENCES iface(id) ON DELETE CASCADE,
  subnet_id BIGINT NOT NULL REFERENCES subnet(id) ON DELETE CASCADE,
  ip TEXT NOT NULL,
  kind TEXT NOT NULL DEFAULT 'dhcp' CHECK (kind IN ('static','dhcp'))
);
CREATE INDEX idx_ip_subnet ON ip_assignment(subnet_id, ip);

CREATE TABLE iface_status (
  iface_id BIGINT PRIMARY KEY REFERENCES iface(id) ON DELETE CASCADE,
  online BOOLEAN NOT NULL DEFAULT FALSE,
  first_seen TEXT,
  last_seen TEXT,
  last_rtt_ms DOUBLE PRECISION,
  missed_sweeps INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE availability_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  iface_id BIGINT NOT NULL REFERENCES iface(id) ON DELETE CASCADE,
  bucket_start TEXT NOT NULL,
  up_count INTEGER NOT NULL DEFAULT 0,
  total_count INTEGER NOT NULL DEFAULT 0,
  UNIQUE (iface_id, bucket_start)
);

CREATE TABLE open_port (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  iface_id BIGINT NOT NULL REFERENCES iface(id) ON DELETE CASCADE,
  port INTEGER NOT NULL,
  proto TEXT NOT NULL DEFAULT 'tcp' CHECK (proto IN ('tcp','udp')),
  service_guess TEXT NOT NULL DEFAULT '',
  first_seen TEXT NOT NULL,
  last_seen TEXT NOT NULL,
  UNIQUE (iface_id, port, proto)
);

CREATE TABLE tag (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  color TEXT NOT NULL DEFAULT '#888888'
);

CREATE TABLE device_tag (
  device_id BIGINT NOT NULL REFERENCES device(id) ON DELETE CASCADE,
  tag_id BIGINT NOT NULL REFERENCES tag(id) ON DELETE CASCADE,
  PRIMARY KEY (device_id, tag_id)
);

CREATE TABLE custom_field (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id BIGINT NOT NULL REFERENCES device(id) ON DELETE CASCADE,
  key TEXT NOT NULL,
  value TEXT NOT NULL DEFAULT '',
  UNIQUE (device_id, key)
);

CREATE TABLE device_link (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id BIGINT NOT NULL REFERENCES device(id) ON DELETE CASCADE,
  label TEXT NOT NULL,
  url TEXT NOT NULL
);

CREATE TABLE event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  type TEXT NOT NULL CHECK (type IN ('device_new','online','offline','ip_changed','scan_error')),
  device_id BIGINT REFERENCES device(id) ON DELETE SET NULL,
  details TEXT NOT NULL DEFAULT ''
);
CREATE INDEX idx_event_ts ON event(ts DESC);

-- "user" is a reserved word in Postgres and must stay quoted; the store's
-- queries quote it too, which SQLite also accepts.
CREATE TABLE "user" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'viewer' CHECK (role IN ('admin','viewer'))
);

CREATE TABLE session (
  token TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  expires_at TEXT NOT NULL
);

CREATE TABLE setting (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE integration_status (
  name TEXT PRIMARY KEY,
  last_run TEXT NOT NULL,
  ok BOOLEAN NOT NULL DEFAULT FALSE,
  detail TEXT NOT NULL DEFAULT '',
  item_count INTEGER NOT NULL DEFAULT 0
);
