-- Personal API tokens: a long-lived bearer credential a script presents in
-- place of a browser session. Like sessions, only the SHA-256 digest of the
-- token is stored, so a copied database or backup carries no working token.
-- A token belongs to a user and acts with that user's role; deleting the user
-- deletes their tokens. expires_at NULL means the token does not expire.
CREATE TABLE api_token (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  token_hash TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL,
  last_used_at TEXT,
  expires_at TEXT
);
CREATE INDEX idx_api_token_user ON api_token(user_id);
