// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// paletteEntry is one fixed command-palette result: a page to open (Href) or
// an action palette.js knows by name (Action). Keys are extra words it
// matches on.
type paletteEntry struct {
	Group, Label, Icon, Href, Action, Keys, Shortcut string
}

// paletteEntries are the palette's fixed results for the signed-in role.
// Admin-only pages and actions are left out for a viewer, as they are from
// the navigation.
func paletteEntries(admin bool) []paletteEntry {
	out := []paletteEntry{
		{Group: "Pages", Label: "Dashboard", Icon: "layout-dashboard", Href: "/", Keys: "home overview", Shortcut: "g h"},
		{Group: "Pages", Label: "Devices", Icon: "monitor", Href: "/devices", Keys: "hosts inventory", Shortcut: "g d"},
		{Group: "Pages", Label: "Subnets", Icon: "network", Href: "/subnets", Keys: "networks grid", Shortcut: "g s"},
		{Group: "Pages", Label: "Events", Icon: "activity", Href: "/events", Keys: "history log", Shortcut: "g e"},
		{Group: "Settings", Label: "Account", Icon: "user", Href: "/settings/account", Keys: "profile password sso"},
		{Group: "Settings", Label: "Sessions", Icon: "clock", Href: "/settings/sessions", Keys: "sign out browsers"},
		{Group: "Settings", Label: "API tokens", Icon: "key", Href: "/settings/tokens", Keys: "token script"},
	}
	if admin {
		out = append(out,
			paletteEntry{Group: "Settings", Label: "Network", Icon: "network", Href: "/settings/network", Keys: "subnets scanning offline presence manage"},
			paletteEntry{Group: "Settings", Label: "Integrations", Icon: "refresh-cw", Href: "/settings/integrations", Keys: "proxmox wireguard pihole adguard opnsense dhcp"},
			paletteEntry{Group: "Settings", Label: "Notifications", Icon: "bell", Href: "/settings/notifications", Keys: "webhook ntfy alerts"},
			paletteEntry{Group: "Settings", Label: "Users", Icon: "user", Href: "/settings/users", Keys: "accounts roles"},
			paletteEntry{Group: "Settings", Label: "Audit log", Icon: "list", Href: "/settings/audit", Keys: "audit history changes"},
			paletteEntry{Group: "Settings", Label: "System", Icon: "server", Href: "/settings/system", Keys: "retention backups about version"},
			paletteEntry{Group: "Actions", Label: "New device", Icon: "plus", Action: "new-device", Keys: "add create", Shortcut: "n"},
			paletteEntry{Group: "Actions", Label: "Scan all subnets", Icon: "radar", Action: "scan-all", Keys: "scan now sweep"},
		)
	}
	return append(out,
		paletteEntry{Group: "Actions", Label: "Find a free IP", Icon: "network", Action: "free-ips", Keys: "free static address unused available", Shortcut: "g f"},
		paletteEntry{Group: "Actions", Label: "Keyboard shortcuts", Icon: "keyboard", Action: "shortcuts", Keys: "help keys", Shortcut: "?"},
		paletteEntry{Group: "Actions", Label: "Theme: follow system", Icon: "sun-moon", Action: "theme-system", Keys: "appearance auto"},
		paletteEntry{Group: "Actions", Label: "Theme: light", Icon: "sun", Action: "theme-light", Keys: "appearance"},
		paletteEntry{Group: "Actions", Label: "Theme: dark", Icon: "moon", Action: "theme-dark", Keys: "appearance"},
	)
}

// palette is the command palette (Ctrl/⌘-K) and the shortcuts help, both
// native dialogs that palette.js opens. Without JavaScript neither ever
// opens and the buttons that would open them stay hidden.
func palette() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<dialog id=\"palette\" class=\"palette\" aria-label=\"Search and jump to\"><div class=\"palette-input\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Icon("search", "icon-lg").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<input id=\"palette-q\" type=\"text\" role=\"combobox\" aria-expanded=\"true\" aria-controls=\"palette-list\" aria-autocomplete=\"list\" aria-label=\"Search devices, subnets and pages\" placeholder=\"Search devices, subnets, pages… or type free\" autocomplete=\"off\" spellcheck=\"false\"> <kbd>Esc</kbd></div><ul id=\"palette-list\" class=\"palette-list\" role=\"listbox\" aria-label=\"Results\"></ul><p class=\"palette-empty\" hidden>No matches.</p><div class=\"palette-foot\"><span><kbd>↑</kbd> <kbd>↓</kbd> move</span> <span><kbd>Enter</kbd> open</span> <span class=\"palette-copy-hint\" hidden><kbd>Shift</kbd> <kbd>Enter</kbd> copy IP</span> <span><kbd>Esc</kbd> close</span></div><template id=\"palette-static\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, e := range paletteEntries(IsAdmin(ctx)) {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<li data-group=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(e.Group)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/views/palette.templ`, Line: 75, Col: 28}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" data-icon=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(e.Icon)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/views/palette.templ`, Line: 75, Col: 49}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" data-href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(e.Href)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/views/palette.templ`, Line: 75, Col: 70}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" data-action=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.ResolveAttributeValue(e.Action)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/views/palette.templ`, Line: 75, Col: 95}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\" data-keys=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.ResolveAttributeValue(e.Keys)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/views/palette.templ`, Line: 75, Col: 116}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\" data-shortcut=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.ResolveAttributeValue(e.Shortcut)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/views/palette.templ`, Line: 75, Col: 145}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var7)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var8 string
			templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(e.Label)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/views/palette.templ`, Line: 75, Col: 157}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</template></dialog> <dialog id=\"shortcuts\" class=\"dialog\" aria-labelledby=\"shortcuts-title\"><div class=\"dh\"><h3 id=\"shortcuts-title\">Keyboard shortcuts</h3><button type=\"button\" class=\"btn btn-quiet btn-icon btn-sm\" data-dialog-close aria-label=\"Close\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Icon("x", "").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</button></div><div class=\"db\"><dl class=\"keys\"><dt><kbd data-mod-key>Ctrl K</kbd></dt><dd>Search and jump to</dd><dt><kbd>/</kbd></dt><dd>Search this page, or open search</dd><dt><kbd>g</kbd> <kbd>h</kbd></dt><dd>Go to the dashboard</dd><dt><kbd>g</kbd> <kbd>d</kbd></dt><dd>Go to devices</dd><dt><kbd>g</kbd> <kbd>s</kbd></dt><dd>Go to subnets</dd><dt><kbd>g</kbd> <kbd>e</kbd></dt><dd>Go to events</dd><dt><kbd>g</kbd> <kbd>f</kbd></dt><dd>Find a free IP</dd>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if IsAdmin(ctx) {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "<dt><kbd>n</kbd></dt><dd>New device</dd>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "<dt><kbd>?</kbd></dt><dd>Show these shortcuts</dd><dt><kbd>Esc</kbd></dt><dd>Close a dialog</dd></dl></div></dialog>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
